"""removed utxo_tx_hash/data_hash from utxo_input_amount and utxo_output_amount and changed all quantity types to Numeric

Revision ID: 0b94d65f554c
Revises: d9d0c41f2114
Create Date: 2025-05-07 20:01:26.367961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b94d65f554c'
down_revision: Union[str, None] = 'd9d0c41f2114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    (op.alter_column
        (
            'cardano_tx_output_amount',
            'quantity',
            existing_type=sa.VARCHAR(),
            type_=sa.Numeric(precision=38, scale=0),
            existing_nullable=False,
            postgresql_using="quantity::numeric(38,0)"
        )
    )
    op.create_foreign_key('fk_utxo_input_tx', 'cardano_tx_utxo_input', 'cardano_transactions', ['hash'], ['hash'])
    op.alter_column(
        'cardano_tx_utxo_input_amount',
        'quantity',
        existing_type=sa.VARCHAR(),
        type_=sa.Numeric(precision=38, scale=0),
        existing_nullable=False,
        postgresql_using="quantity::numeric(38,0)",
    )
    op.drop_column('cardano_tx_utxo_input_amount', 'tx_utxo_hash')
    op.create_foreign_key('fk_utxo_output_tx', 'cardano_tx_utxo_output', 'cardano_transactions', ['hash'], ['hash'])
    op.alter_column(
        'cardano_tx_utxo_output_amount',
        'quantity',
        existing_type=sa.VARCHAR(),
        type_=sa.Numeric(precision=38, scale=0),
        existing_nullable=False,
        postgresql_using="quantity::numeric(38,0)",
    )
    op.drop_column('cardano_tx_utxo_output_amount', 'tx_utxo_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cardano_tx_utxo_output_amount', sa.Column('tx_utxo_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column(
        'cardano_tx_utxo_output_amount',
        'quantity',
        existing_type=sa.Numeric(precision=38, scale=0),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_constraint('fk_utxo_output_tx', 'cardano_tx_utxo_output', type_='foreignkey')
    op.add_column('cardano_tx_utxo_input_amount', sa.Column('tx_utxo_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('cardano_tx_utxo_input_amount', 'quantity',
               existing_type=sa.Numeric(precision=38, scale=0),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint('fk_utxo_input_tx', 'cardano_tx_utxo_input', type_='foreignkey')
    op.alter_column('cardano_tx_output_amount', 'quantity',
               existing_type=sa.Numeric(precision=38, scale=0),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
