"""changed the columns of s3_to_db_import_status table

Revision ID: 2d05878fcdc6
Revises: a6f2b5d040a9
Create Date: 2025-04-01 15:21:42.003999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d05878fcdc6'
down_revision: Union[str, None] = 'a6f2b5d040a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('s3_to_db_import_status', sa.Column('block_height', sa.Integer(), nullable=False))
    op.drop_column('s3_to_db_import_status', 'file_modified_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('s3_to_db_import_status', sa.Column('file_modified_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('s3_to_db_import_status', 'block_height')
    # ### end Alembic commands ###
