"""changed data_hash of tx_utxo_amount to tx_data_hash

Revision ID: 3b20356f58de
Revises: 4a399294a2e1
Create Date: 2025-05-06 03:03:19.296957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b20356f58de'
down_revision: Union[str, None] = '4a399294a2e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cardano_tx_utxo_output_amount', sa.Column('tx_utxo_hash', sa.String(), nullable=False))
    op.drop_column('cardano_tx_utxo_output_amount', 'data_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cardano_tx_utxo_output_amount', sa.Column('data_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('cardano_tx_utxo_output_amount', 'tx_utxo_hash')
    # ### end Alembic commands ###
