"""added parent_id for tx_utxo_input_amt and tx_utxo_output_amt tables

Revision ID: 4a399294a2e1
Revises: b1fe9c6fa97c
Create Date: 2025-05-06 02:45:37.595053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a399294a2e1'
down_revision: Union[str, None] = 'b1fe9c6fa97c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cardano_tx_utxo_input_amount', sa.Column('parent_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'cardano_tx_utxo_input_amount', 'cardano_tx_utxo_input', ['parent_id'], ['id'])
    op.add_column('cardano_tx_utxo_output_amount', sa.Column('parent_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'cardano_tx_utxo_output_amount', 'cardano_tx_utxo_output', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cardano_tx_utxo_output_amount', type_='foreignkey')
    op.drop_column('cardano_tx_utxo_output_amount', 'parent_id')
    op.drop_constraint(None, 'cardano_tx_utxo_input_amount', type_='foreignkey')
    op.drop_column('cardano_tx_utxo_input_amount', 'parent_id')
    # ### end Alembic commands ###
