"""create sqlalchemy tables

Revision ID: 85caa57ec4f3
Revises: 
Create Date: 2025-03-30 11:02:32.434389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85caa57ec4f3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cardano_block_transactions',
    sa.Column('block', sa.String(), nullable=False),
    sa.Column('tx_hash', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('block')
    )
    op.create_table('cardano_blocks',
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('epoch', sa.Integer(), nullable=True),
    sa.Column('epoch_slot', sa.Integer(), nullable=True),
    sa.Column('slot_leader', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('tx_count', sa.Integer(), nullable=False),
    sa.Column('output', sa.String(), nullable=True),
    sa.Column('fees', sa.String(), nullable=True),
    sa.Column('block_vrf', sa.String(), nullable=True),
    sa.Column('op_cert', sa.String(), nullable=True),
    sa.Column('op_cert_counter', sa.String(), nullable=True),
    sa.Column('previous_block', sa.String(), nullable=True),
    sa.Column('next_block', sa.String(), nullable=True),
    sa.Column('confirmations', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('height')
    )
    op.create_table('cardano_transactions',
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('block', sa.String(), nullable=False),
    sa.Column('block_height', sa.Integer(), nullable=False),
    sa.Column('block_time', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('fees', sa.String(), nullable=False),
    sa.Column('deposit', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('invalid_before', sa.String(), nullable=True),
    sa.Column('invalid_hereafter', sa.String(), nullable=True),
    sa.Column('utxo_count', sa.Integer(), nullable=False),
    sa.Column('withdrawal_count', sa.Integer(), nullable=False),
    sa.Column('mir_cert_count', sa.Integer(), nullable=False),
    sa.Column('delegation_count', sa.Integer(), nullable=False),
    sa.Column('stake_cert_count', sa.Integer(), nullable=False),
    sa.Column('pool_update_count', sa.Integer(), nullable=False),
    sa.Column('pool_retire_count', sa.Integer(), nullable=False),
    sa.Column('asset_mint_or_burn_count', sa.Integer(), nullable=False),
    sa.Column('redeemer_count', sa.Integer(), nullable=False),
    sa.Column('valid_contract', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_table('cardano_tx_output_amount',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('quantity', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cardano_tx_utxo',
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('block_height', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_table('cardano_tx_utxo_input',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('tx_utxo_hash', sa.String(), nullable=False),
    sa.Column('output_index', sa.Integer(), nullable=False),
    sa.Column('data_hash', sa.String(), nullable=True),
    sa.Column('inline_datum', sa.String(), nullable=True),
    sa.Column('reference_script_hash', sa.String(), nullable=True),
    sa.Column('collateral', sa.Boolean(), nullable=False),
    sa.Column('reference', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cardano_tx_utxo_input_amount',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tx_utxo_hash', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('quantity', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cardano_tx_utxo_output',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('output_index', sa.Integer(), nullable=False),
    sa.Column('data_hash', sa.String(), nullable=True),
    sa.Column('inline_datum', sa.String(), nullable=True),
    sa.Column('collateral', sa.Boolean(), nullable=False),
    sa.Column('reference_script_hash', sa.String(), nullable=True),
    sa.Column('consumed_by_tx', sa.String(), nullable=True),
    sa.Column('created_at', sa.NullType(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cardano_tx_utxo_output_amount',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tx_utxo_hash', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('quantity', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('s3_to_db',
    sa.Column('table', sa.String(), nullable=False),
    sa.Column('file_modified_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('table', 'file_modified_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('s3_to_db')
    op.drop_table('cardano_tx_utxo_output_amount')
    op.drop_table('cardano_tx_utxo_output')
    op.drop_table('cardano_tx_utxo_input_amount')
    op.drop_table('cardano_tx_utxo_input')
    op.drop_table('cardano_tx_utxo')
    op.drop_table('cardano_tx_output_amount')
    op.drop_table('cardano_transactions')
    op.drop_table('cardano_blocks')
    op.drop_table('cardano_block_transactions')
    # ### end Alembic commands ###
