"""change in columns for s3_to_db_import_status table from block_height to file_modified_date

Revision ID: 9bc75f60b57c
Revises: 2d05878fcdc6
Create Date: 2025-04-07 18:13:01.832732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bc75f60b57c'
down_revision: Union[str, None] = '2d05878fcdc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('s3_to_db_import_status', sa.Column('file_modified_date', sa.DateTime(), nullable=False))
    op.drop_column('s3_to_db_import_status', 'block_height')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('s3_to_db_import_status', sa.Column('block_height', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('s3_to_db_import_status', 'file_modified_date')
    # ### end Alembic commands ###
