"""edited block_time from integer to  DateTime for cardano_transactions

Revision ID: b0673669b6c8
Revises: d0b7a8a96849
Create Date: 2025-05-02 13:33:52.252717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0673669b6c8'
down_revision: Union[str, None] = 'd0b7a8a96849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'cardano_transactions',
        'block_time',
        existing_type=sa.INTEGER(),
        postgresql_using="to_timestamp(block_time)",
        type_=sa.DateTime(),
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'cardano_transactions',
        'block_time',
        existing_type=sa.DateTime(),
        type_=sa.INTEGER(),
        postgresql_using="extract(epoch FROM block_time)",
        existing_nullable=False
    )
    # ### end Alembic commands ###
