"""removed block_height column in cardano_tx_utxo_table

Revision ID: b1fe9c6fa97c
Revises: d063573f99e5
Create Date: 2025-05-06 00:23:52.743396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1fe9c6fa97c'
down_revision: Union[str, None] = 'd063573f99e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cardano_tx_utxo', 'block_height')
    op.add_column('cardano_tx_utxo_output_amount', sa.Column('data_hash', sa.String(), nullable=False))
    op.drop_column('cardano_tx_utxo_output_amount', 'tx_utxo_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cardano_tx_utxo_output_amount', sa.Column('tx_utxo_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('cardano_tx_utxo_output_amount', 'data_hash')
    op.add_column('cardano_tx_utxo', sa.Column('block_height', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
