"""changed valid_contract column of cardano_transactions table from type Integer to Boolean

Revision ID: d063573f99e5
Revises: b0673669b6c8
Create Date: 2025-05-02 13:55:53.778967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd063573f99e5'
down_revision: Union[str, None] = 'b0673669b6c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'cardano_transactions',
        'valid_contract',
        existing_type=sa.INTEGER(),
        type_=sa.Boolean(),
        postgresql_using="valid_contract::boolean",
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'cardano_transactions',
        'valid_contract',
        existing_type=sa.Boolean(),
        type_=sa.INTEGER(),
        postgresql_using="valid_contract::int",
        existing_nullable=False
    )
    # ### end Alembic commands ###
