"""updated alembic tables - utxo input amount and utxo output amount

Revision ID: d9d0c41f2114
Revises: 3b20356f58de
Create Date: 2025-05-07 19:13:41.717255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9d0c41f2114'
down_revision: Union[str, None] = '3b20356f58de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cardano_tx_utxo_output_amount', 'tx_utxo_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cardano_tx_utxo_output_amount', 'tx_utxo_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
